services:
  database:
    image: 'postgres:17.2'
    container_name: 'database'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
      POSTGRES_USER: user
    ports:
      - "5432:5432"
    volumes:
      - "./docker/sql_init/init:/docker-entrypoint-initdb.d"
      - db_data:/var/lib/postgres
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d db"]
      interval: 5s
      timeout: 5s
      retries: 100

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'app'
    environment:
      DB_HOST: database  # Use the service name of the database container
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: db
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
